# Generated by Django 5.2.17 on 2026-08-07 19:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable label, e.g. 'Production AI Integration'.", max_length=100)),
                ('prefix', models.CharField(editable=False, help_text='First 8 characters of the raw key — safe for display and identification.', max_length=8)),
                ('hashed_key', models.CharField(editable=False, help_text='PBKDF2-SHA256 hash of the full raw key. Never store or display the raw key.', max_length=255)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to revoke the key without deleting the audit record.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Updated on each successful API key authentication.', null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_active'], name='apikey_org_active_idx')],
            },
        ),
    ]
