# Generated by Django 5.2.17 on 2026-08-07 19:25

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'verbose_name': 'Organization Member', 'verbose_name_plural': 'Organization Members'},
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Deactivate to suspend this user's access to the workspace without revoking the membership record (preserves audit history)."),
        ),
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — prevents tenant ID enumeration.', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inactive organizations are suspended — all workspace header access attempts return 403 regardless of membership.'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='URL-safe unique identifier for this organization.', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member')], db_index=True, default='member', max_length=20),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='org_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['is_active'], name='org_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'user'], name='member_org_user_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['role'], name='member_role_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['is_active'], name='member_is_active_idx'),
        ),
    ]
