# Generated by Django 5.2.17 on 2026-08-07 20:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_organization_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID primary key — prevents ID enumeration attacks.', primary_key=True, serialize=False)),
                ('task_id', models.CharField(db_index=True, help_text='Celery background task ID for asynchronous execution tracking.', max_length=255)),
                ('prompt', models.TextField(help_text='Input text prompt sent to the LLM.')),
                ('response', models.JSONField(blank=True, help_text='Structured JSON output returned by the LLM upon completion.', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], db_index=True, default='PENDING', help_text='Current lifecycle state of the background task.', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Sanitized error details if execution failed.', null=True)),
                ('tokens_used', models.IntegerField(default=0, help_text='Total tokens consumed (prompt + completion tokens).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the request log entry was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last updated.')),
                ('organization', models.ForeignKey(help_text='The tenant organization that owns this AI request log.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to='organizations.organization')),
                ('user', models.ForeignKey(help_text='The user who initiated this AI generation request.', on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Request Log',
                'verbose_name_plural': 'AI Request Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'task_id'], name='ailog_org_task_idx'), models.Index(fields=['organization', 'status'], name='ailog_org_status_idx'), models.Index(fields=['task_id'], name='ailog_task_id_idx')],
            },
        ),
    ]
